import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "test/database-connectivity.test.ts",
      "test/migrations.integration.test.ts",
      "test/rm005-schema.integration.test.ts",
      "test/rm006-schema.integration.test.ts",
      "test/rm007-schema.integration.test.ts",
      "test/rm008-bootstrap.integration.test.ts",
      "test/rm009-database.integration.test.ts",
      "test/rm015-registration.database.integration.test.ts",
      "test/rm016-login.database.integration.test.ts",
      "test/rm017-users.database.integration.test.ts",
      "test/rm018-auth-users.database.integration.test.ts",
      "test/rm019-lookups.database.integration.test.ts",
      "test/rm020-listing-create.database.integration.test.ts",
      "test/rm021-owner-listing-read.database.integration.test.ts",
      "test/rm022-phase4.database.integration.test.ts",
      "test/rm023-listing-update.database.integration.test.ts",
      "test/rm024-current-moderation-reason.database.integration.test.ts",
      "test/rm025-listing-submit.database.integration.test.ts",
      "test/rm026-listing-lifecycle-actions.database.integration.test.ts",
      "test/rm027-listing-delete.database.integration.test.ts",
      "test/rm028-listing-lifecycle.database.integration.test.ts",
      "test/rm028-listing-concurrency.database.integration.test.ts",
      "test/rm029-listing-image-upload.database.integration.test.ts",
      "test/rm030-listing-image-delete.database.integration.test.ts",
      "test/rm031-listing-image-order.database.integration.test.ts",
      "test/rm032-image-lifecycle.database.integration.test.ts",
      "test/rm032-image-concurrency.database.integration.test.ts",
      "test/rm032-image-provider.database.integration.test.ts",
      "test/rm035-public-search.database.integration.test.ts",
      "test/rm036-public-search.database.integration.test.ts",
      "test/rm037-public-listing-detail.database.integration.test.ts",
      "test/rm038-public-discovery.database.integration.test.ts",
      "test/rm039-favorite.database.integration.test.ts",
      "test/rm040-favorite.database.integration.test.ts",
      "test/rm040-favorite-concurrency.database.integration.test.ts",
      "test/rm041-admin-listing-read.database.integration.test.ts",
      "test/rm042-moderation-action.database.integration.test.ts",
      "test/rm043-admin-user.database.integration.test.ts",
      "test/rm044-moderation-matrix.database.integration.test.ts",
      "test/rm044-moderation-concurrency.database.integration.test.ts",
      "test/rm044-activation-visibility.database.integration.test.ts",
      "test/rm053-fresh-backend.database.integration.test.ts",
      "test/rm053-lifecycle-visibility.database.integration.test.ts"
    ],
    exclude: ["node_modules/**", "dist/**", "coverage/**"],
    clearMocks: true,
    restoreMocks: true,
    fileParallelism: false,
    testTimeout: 15_000
  }
});
